[package]
name = "xcalgo"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
rand = "0.8"
num-bigint = "0.4"
num-traits = "0.2"
petgraph = "0.6"
zstd = "0.13"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "xca_bench"
harness = false
